import { Component } from '@angular/core';
import { DynamicTable } from '../../shared/dynamic-table/dynamic-table';
import { TableConfig } from '../../shared/dynamic-table/table.interface';

@Component({
  selector: 'app-winner',
  standalone: true,
  imports: [DynamicTable],
  templateUrl: './winner.html',
  styleUrl: './winner.css',
})
export class Winner {
  tableConfig: TableConfig = {
    columns: [
      {
        key: 'employeeName',
        label: 'Employee Name',
        type: 'groupToggle',
        group: 'employeeDetails',
      },

      { key: 'grade', label: 'Grade', hidden: true, expandable: true, group: 'employeeDetails' },
      {
        key: 'function',
        label: 'Function',
        hidden: true,
        expandable: true,
        group: 'employeeDetails',
      },
      {
        key: 'account',
        label: 'Account',
        hidden: true,
        expandable: true,
        group: 'employeeDetails',
      },
      {
        key: 'process',
        label: 'Process',
        hidden: true,
        expandable: true,
        group: 'employeeDetails',
      },

      {
        key: 'supervisor',
        label: 'Supervisor Name',
        hidden: true,
        sortable: true,
        expandable: true,
        width: 'w-40',
        group: 'employeeDetails',
      },
      { key: 'nominator', label: 'Nominator Name', sortable: true, width: 'w-40' },
      { key: 'nominationDate', label: 'Nomination Date', sortable: true, width: 'w-36' },

      {
        key: 'nominatorRemark',
        label: 'Nominator Remark',
        hidden: false,
        expandable: false,
        type: 'groupToggle',
        group: 'remarksGroup',
      },
      {
        key: 'evaluatorRemark',
        label: 'Evaluator Remark',
        hidden: true,
        expandable: true,
        group: 'remarksGroup',
      },
      {
        key: 'selectorRemark',
        label: 'Selector Remark',
        hidden: true,
        expandable: true,
        group: 'remarksGroup',
      },
      {
        key: 'appreciation',
        label: 'Appreciation',
        type: 'appreciation',
        width: 'w-28',
        appreciationMap: {
          single: '🏆',
          multi: '🏆 🎖️',
        },
      },

      {
        key: 'status',
        label: 'Status',
        type: 'status',
        sortable: true,
        width: 'w-28',
        statusMap: {
          Pending: 'bg-orange-100 text-orange-700',
          Approved: 'bg-green-100 text-green-700',
          Selection: 'bg-blue-100 text-blue-700',
        },
      },

      {
        key: 'action',
        label: 'Action',
        type: 'action',
        actionLabel: 'Selection',
        width: 'w-32',
        sticky: 'right',
        stickyOffset: '0',
      },
    ],

    filters: [
      {
        key: 'function',
        label: 'Function',
        options: ['All', 'Clinical Document Management', 'Quality Assurance', 'Patient Care'],
      },
      {
        key: 'account',
        label: 'Account',
        options: ['All', 'ADVANCED UROLOGY INSTITUTE', 'WellMed', 'HealthCorp'],
      },
      { key: 'process', label: 'Process', options: ['All', 'PVS', 'STACKS', 'QUALITY'] },
      {
        key: 'supervisor',
        label: 'Manager',
        options: ['All', 'Yogesh Raul', 'Pooja Jawale', 'Amit Kumar'],
      },
    ],

    data: [
      {
        id: '76766',
        employeeName: 'Mayuri Indave (76766)',
        grade: '13',
        function: 'Clinical Document Management',
        account: 'ADVANCED UROLOGY INSTITUTE',
        process: 'PVS',
        supervisorName: 'Yogesh Raul',
        nominationDate: '2026-01-13',
        nominatorRemark:
          'She has achieved a productivity of 143 % with 99.94% quality and also contributed in automation project.',
        evaluatorRemark: '-',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '54330',
        employeeName: 'Akshay Borhade (54330)',
        grade: '11',
        function: 'Clinical Document Management',
        account: 'WellMed',
        process: 'STACKS',
        supervisorName: 'Pooja Jawale',
        nominationDate: '2026-01-13',
        nominatorRemark: 'Akshay has achieved a productivity of 178.62% with 100% quality.',
        evaluatorRemark: 'The nomination is verified and approved as per policy',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '52113',
        employeeName: 'Anuj Jaiswar (52113)',
        grade: '11',
        function: 'Clinical Document Management',
        account: 'WellMed',
        process: 'STACKS',
        supervisorName: 'Pooja Jawale',
        nominationDate: '2026-01-13',
        nominatorRemark: 'Anuj has achieved a productivity of 107.7% with 100% quality.',
        evaluatorRemark: 'The nomination is verified and approved as per policy',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '76766',
        employeeName: 'Mayuri Indave (76766)',
        grade: '13',
        function: 'Clinical Document Management',
        account: 'ADVANCED UROLOGY INSTITUTE',
        process: 'PVS',
        supervisorName: 'Yogesh Raul',
        nominationDate: '2026-01-13',
        nominatorRemark:
          'She has achieved a productivity of 143 % with 99.94% quality and also contributed in automation project.',
        evaluatorRemark: '-',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '54330',
        employeeName: 'Akshay Borhade (54330)',
        grade: '11',
        function: 'Clinical Document Management',
        account: 'WellMed',
        process: 'STACKS',
        supervisorName: 'Pooja Jawale',
        nominationDate: '2026-01-13',
        nominatorRemark: 'Akshay has achieved a productivity of 178.62% with 100% quality.',
        evaluatorRemark: 'The nomination is verified and approved as per policy',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '52113',
        employeeName: 'Anuj Jaiswar (52113)',
        grade: '11',
        function: 'Clinical Document Management',
        account: 'WellMed',
        process: 'STACKS',
        supervisorName: 'Pooja Jawale',
        nominationDate: '2026-01-13',
        nominatorRemark: 'Anuj has achieved a productivity of 107.7% with 100% quality.',
        evaluatorRemark: 'The nomination is verified and approved as per policy',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '76766',
        employeeName: 'Mayuri Indave (76766)',
        grade: '13',
        function: 'Clinical Document Management',
        account: 'ADVANCED UROLOGY INSTITUTE',
        process: 'PVS',
        supervisorName: 'Yogesh Raul',
        nominationDate: '2026-01-13',
        nominatorRemark:
          'She has achieved a productivity of 143 % with 99.94% quality and also contributed in automation project.',
        evaluatorRemark: '-',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '54330',
        employeeName: 'Akshay Borhade (54330)',
        grade: '11',
        function: 'Clinical Document Management',
        account: 'WellMed',
        process: 'STACKS',
        supervisorName: 'Pooja Jawale',
        nominationDate: '2026-01-13',
        nominatorRemark: 'Akshay has achieved a productivity of 178.62% with 100% quality.',
        evaluatorRemark: 'The nomination is verified and approved as per policy',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '52113',
        employeeName: 'Anuj Jaiswar (52113)',
        grade: '11',
        function: 'Clinical Document Management',
        account: 'WellMed',
        process: 'STACKS',
        supervisorName: 'Pooja Jawale',
        nominationDate: '2026-01-13',
        nominatorRemark: 'Anuj has achieved a productivity of 107.7% with 100% quality.',
        evaluatorRemark: 'The nomination is verified and approved as per policy',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '76766',
        employeeName: 'Mayuri Indave (76766)',
        grade: '13',
        function: 'Clinical Document Management',
        account: 'ADVANCED UROLOGY INSTITUTE',
        process: 'PVS',
        supervisorName: 'Yogesh Raul',
        nominationDate: '2026-01-13',
        nominatorRemark:
          'She has achieved a productivity of 143 % with 99.94% quality and also contributed in automation project.',
        evaluatorRemark: '-',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '54330',
        employeeName: 'Akshay Borhade (54330)',
        grade: '11',
        function: 'Clinical Document Management',
        account: 'WellMed',
        process: 'STACKS',
        supervisorName: 'Pooja Jawale',
        nominationDate: '2026-01-13',
        nominatorRemark: 'Akshay has achieved a productivity of 178.62% with 100% quality.',
        evaluatorRemark: 'The nomination is verified and approved as per policy',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '52113',
        employeeName: 'Anuj Jaiswar (52113)',
        grade: '11',
        function: 'Clinical Document Management',
        account: 'WellMed',
        process: 'STACKS',
        supervisorName: 'Pooja Jawale',
        nominationDate: '2026-01-13',
        nominatorRemark: 'Anuj has achieved a productivity of 107.7% with 100% quality.',
        evaluatorRemark: 'The nomination is verified and approved as per policy',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '54330',
        employeeName: 'Akshay Borhade (54330)',
        grade: '11',
        function: 'Clinical Document Management',
        account: 'WellMed',
        process: 'STACKS',
        supervisorName: 'Pooja Jawale',
        nominationDate: '2026-01-13',
        nominatorRemark: 'Akshay has achieved a productivity of 178.62% with 100% quality.',
        evaluatorRemark: 'The nomination is verified and approved as per policy',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '52113',
        employeeName: 'Anuj Jaiswar (52113)',
        grade: '11',
        function: 'Clinical Document Management',
        account: 'WellMed',
        process: 'STACKS',
        supervisorName: 'Pooja Jawale',
        nominationDate: '2026-01-13',
        nominatorRemark: 'Anuj has achieved a productivity of 107.7% with 100% quality.',
        evaluatorRemark: 'The nomination is verified and approved as per policy',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '76766',
        employeeName: 'Mayuri Indave (76766)',
        grade: '13',
        function: 'Clinical Document Management',
        account: 'ADVANCED UROLOGY INSTITUTE',
        process: 'PVS',
        supervisorName: 'Yogesh Raul',
        nominationDate: '2026-01-13',
        nominatorRemark:
          'She has achieved a productivity of 143 % with 99.94% quality and also contributed in automation project.',
        evaluatorRemark: '-',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '54330',
        employeeName: 'Akshay Borhade (54330)',
        grade: '11',
        function: 'Clinical Document Management',
        account: 'WellMed',
        process: 'STACKS',
        supervisorName: 'Pooja Jawale',
        nominationDate: '2026-01-13',
        nominatorRemark: 'Akshay has achieved a productivity of 178.62% with 100% quality.',
        evaluatorRemark: 'The nomination is verified and approved as per policy',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '52113',
        employeeName: 'Anuj Jaiswar (52113)',
        grade: '11',
        function: 'Clinical Document Management',
        account: 'WellMed',
        process: 'STACKS',
        supervisorName: 'Pooja Jawale',
        nominationDate: '2026-01-13',
        nominatorRemark: 'Anuj has achieved a productivity of 107.7% with 100% quality.',
        evaluatorRemark: 'The nomination is verified and approved as per policy',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '76766',
        employeeName: 'Mayuri Indave (76766)',
        grade: '13',
        function: 'Clinical Document Management',
        account: 'ADVANCED UROLOGY INSTITUTE',
        process: 'PVS',
        supervisorName: 'Yogesh Raul',
        nominationDate: '2026-01-13',
        nominatorRemark:
          'She has achieved a productivity of 143 % with 99.94% quality and also contributed in automation project.',
        evaluatorRemark: '-',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '54330',
        employeeName: 'Akshay Borhade (54330)',
        grade: '11',
        function: 'Clinical Document Management',
        account: 'WellMed',
        process: 'STACKS',
        supervisorName: 'Pooja Jawale',
        nominationDate: '2026-01-13',
        nominatorRemark: 'Akshay has achieved a productivity of 178.62% with 100% quality.',
        evaluatorRemark: 'The nomination is verified and approved as per policy',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '52113',
        employeeName: 'Anuj Jaiswar (52113)',
        grade: '11',
        function: 'Clinical Document Management',
        account: 'WellMed',
        process: 'STACKS',
        supervisorName: 'Pooja Jawale',
        nominationDate: '2026-01-13',
        nominatorRemark: 'Anuj has achieved a productivity of 107.7% with 100% quality.',
        evaluatorRemark: 'The nomination is verified and approved as per policy',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '76766',
        employeeName: 'Mayuri Indave (76766)',
        grade: '13',
        function: 'Clinical Document Management',
        account: 'ADVANCED UROLOGY INSTITUTE',
        process: 'PVS',
        supervisorName: 'Yogesh Raul',
        nominationDate: '2026-01-13',
        nominatorRemark:
          'She has achieved a productivity of 143 % with 99.94% quality and also contributed in automation project.',
        evaluatorRemark: '-',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '54330',
        employeeName: 'Akshay Borhade (54330)',
        grade: '11',
        function: 'Clinical Document Management',
        account: 'WellMed',
        process: 'STACKS',
        supervisorName: 'Pooja Jawale',
        nominationDate: '2026-01-13',
        nominatorRemark: 'Akshay has achieved a productivity of 178.62% with 100% quality.',
        evaluatorRemark: 'The nomination is verified and approved as per policy',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
      {
        id: '52113',
        employeeName: 'Anuj Jaiswar (52113)',
        grade: '11',
        function: 'Clinical Document Management',
        account: 'WellMed',
        process: 'STACKS',
        supervisorName: 'Pooja Jawale',
        nominationDate: '2026-01-13',
        nominatorRemark: 'Anuj has achieved a productivity of 107.7% with 100% quality.',
        evaluatorRemark: 'The nomination is verified and approved as per policy',
        appreciation: ['🏆', '🎁'],
        status: 'Pending',
      },
    ],
    pageSizeOptions: [5, 10, 25],
  };

  handleAction(row: any) {
    console.log('Row action clicked:', row);
  }
}
